name: Import Twitter RSS into Hugo

on:
  schedule:
    - cron: '0 6 * * *'  # Every day at 6 AM UTC (you can adjust)
  workflow_dispatch:  # Allow manual triggering

jobs:
  fetch-and-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install feedparser
      run: pip install feedparser

    - name: Run RSS import script
      run: python /twitter_rss_to_hugo.py

    - name: Commit and push changes
      run: |
        git config --global user.name 'ChiappiniLab Bot'
        git config --global user.email 'github-actions@users.noreply.github.com'
        git add content/news/
        git commit -m "🤖 Import new Twitter posts via RSS" || echo "No changes"
        git push
